# Generated by Django 5.2.4 on 2025-07-10 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoommatePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_from', models.DateField()),
                ('lease_duration', models.PositiveIntegerField(help_text='Lease duration in months')),
                ('room_type', models.CharField(choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('apartment', 'Entire Apartment')], max_length=50)),
                ('preferred_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('A', 'Any')], default='A', max_length=1)),
                ('current_occupants', models.PositiveIntegerField(default=1)),
                ('total_occupants', models.PositiveIntegerField(default=2)),
                ('has_furniture', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=True)),
                ('is_pets_allowed', models.BooleanField(default=False)),
                ('is_smoking_allowed', models.BooleanField(default=False)),
                ('occupation', models.CharField(choices=[('student', 'Student'), ('working', 'Working Professional'), ('other', 'Other')], default='student', max_length=50)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roommate Post',
                'verbose_name_plural': 'Roommate Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoommateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='roommate.roommatepost')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
