# Generated by Django 4.1.13 on 2025-08-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommateimage',
            name='image',
            field=models.ImageField(upload_to='roommate/'),
        ),
    ]
